# Nombre del proyecto
spring.application.name=banco-fraude

# Configuración de la base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web de H2 para revisar las tablas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Crear las tablas automáticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
